[package]
name = "dynamic_services_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
once_cell = "1"
syn = { version = "2.0", features = [ "extra-traits", "full" ]}
quote = "1.0"
proc-macro2 = "1.0"
serde_json = "1.0"